window.UMA_CONFIG = {
  storeUrl: "https://www.meesho.com/UmaHomeArtss?_ms=3.0.1",
  whatsappNumber: "6267291315",
  products: [
    {id:"vastu-fish", name:"Vastu Fish", category:"Vastu", description:"A graceful decorative accent for home or office.", image:"images/vastu-fish.jpeg", meeshoUrl:"https://www.meesho.com/golden-vastu-fish-showpiece-feng-shui-lucky-wealth-fish-statue-home-office-decor-premium-gift-item/p/gpow44", featured:true},
    {id:"lucky-vastu-horse", name:"Lucky Vastu Horse", category:"Vastu", description:"A golden Feng Shui horse showpiece for home, office or gifting.", image:"images/lucky-vastu-horse.jpeg", meeshoUrl:"https://www.meesho.com/lucky-golden-vastu-victory-horse-idol-for-money-success-wealth-prosperity-happiness-feng-shui-running-horse-with-coins-vastu-home-office-study-room-temple-mandir-desk-showpiece-gifts-collectibles/p/ecse3j", featured:true},
    {id:"golden-vastu-tortoise", name:"Golden Vastu Tortoise", category:"Vastu", description:"A three-generation Feng Shui tortoise showpiece for home or office décor.", image:"images/golden-vastu-tortoise.jpeg", meeshoUrl:"https://www.meesho.com/golden-feng-shui-tortoise-for-home-office-vastu-three-generation-turtle-showpiece-for-wealth-luck-prosperity/p/gp3vqt", featured:true},
    {id:"lord-krishna-statue", name:"Lord Krishna Decorative Statue", category:"Polyresin Statues", description:"A detailed Lord Krishna showpiece for home décor, pooja spaces or gifting.", image:"images/lord-krishna-statue.jpeg", meeshoUrl:"https://www.meesho.com/s/p/coucjy?utm_source=s_cc", featured:true},
    {id:"mini-monk-buddha-set", name:"Set of 4 Mini Monk Buddha Showpieces", category:"Polyresin Statues", description:"A charming set of four mini monk Buddha showpieces for home, office or gifting.", image:"images/mini-monk-buddha-set.png", meeshoUrl:"https://www.meesho.com/set-of-4-mini-monk-buddha-showpiece-225-inch-polyresin-decorative-idol-for-home-office/p/cqd1s1", featured:true},
    {id:"lord-jagannath-idol", name:"Lord Jagannath Idol", category:"Polyresin Statues", description:"A detailed Lord Jagannath idol for pooja spaces, home décor or spiritual gifting.", image:"images/lord-jagannath-idol.jpeg", meeshoUrl:"https://www.meesho.com/lord-jagannath-idol-4-inch-murti-for-home-temple-mandir-small-decorative-god-statue-for-pooja-rome-office-desk-study-table-car-dashboard-spiritual-gift-item/p/d58hsx", featured:true},
    {id:"lord-ganesh-idol", name:"Lord Ganesh Idol", category:"Polyresin Statues", description:"A premium Lord Ganesh idol for home décor, pooja rooms, office desks or gifting.", image:"images/lord-ganesh-idol.jpeg", meeshoUrl:"https://www.meesho.com/lord-ganesh-idol-for-car-dashboard-ganpati-bappa-murti-for-home-decor-puja-room-small-ganesh-statue-for-office-desk-vastu-ganesha-gift-item-premium-finish/p/d49i8b", featured:true},
    {id:"golden-black-buddha", name:"Golden & Black Buddha Idol", category:"Polyresin Statues", description:"An 8-inch Buddha idol with an elegant golden and black finish for home décor or gifting.", image:"images/golden-black-buddha.jpeg", meeshoUrl:"https://www.meesho.com/8-inch-buddha-idol-for-home-decor-golden-black-showpiece-pooja-room-statue-gift-for-housewarming-meditation/p/cuoe19", featured:true},
    {id:"birds-mdf-wall-decor", name:"Elegant Birds MDF Wall Decor", category:"MDF Wall Hangings", description:"A stylish birds wall hanging for living rooms, bedrooms, halls or home décor.", image:"images/birds-mdf-wall-decor.png", meeshoUrl:"https://www.meesho.com/elegant-stylish-birds-mdf-wall-decor-wall-hanging-for-living-room-bedroom-hall-home-decoration-139-inch-premium-quality/p/disraa", featured:true}
  ]
};
